[book]
authors = ["Bartłomiej Kuras"]
language = "en"
multilingual = false
src = "src"
title = "CosmWasm book"
description = "Guide to building CosmWasm smart contracts"

[rust]
edition = "2021"

[preprocessor.plantuml]
plantuml-cmd = "plantuml"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
